- id: metriport
  group: FHIR HIE API
  status: active    
  name: Metriport
  description: Metriport is a FHIR HIE API that provides access to patient health records and clinical data.        
  logo: https://assets-global.website-files.com/640036547d68f8c201789d8c/640036e90b4a44838695e030_metriport-logo.png
  react_component: 'akello-app-config'
  configs:
    API URL:
    Secret Key:
- id: fhirqueryscore
  group: FHIR
  status: active
  name: FHIR Query Score
  description: FHIR Query Score
  logo: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Slack_icon_2019.svg/2048px-Slack_icon_2019.svg.png
  react_component: 'fhir-query-score'
  api_url: 
  configs:
