[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "akello_apps"
version = "0.0.1"
authors = [
  { name="Vijay Selvaraj", email="vijay@akellohealth.com" },
]
description = "Akello Apps"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    "Programming Language :: Python :: 3",
]

dependencies = [
]

[project.urls]
Homepage = "https://akello.io"
Issues = "https://github.com/akello-io/akello/issues"