[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "akello"
version = "0.0.18"
authors = [
  { name="Vijay Selvaraj", email="vijay@akellohealth.com" },
]
description = "FastAPI server akello.io"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    "Programming Language :: Python :: 3",
]
dependencies = [
    'fastapi',
    'boto3',
    'pydantic',
    'pydantic-settings',
    'fastapi_cognito',
    'uvicorn',
    'requests',
    'mangum',
    'aws_lambda_powertools',
]

[project.urls]
Homepage = "https://akello.io"
Issues = "https://github.com/akello-io/akello/issues"