[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["akellocli"]

[project]
name = "akellocli"
version = "0.0.5"
authors = [
  { name="Vijay Selvaraj", email="vijay@akellohealth.com" },
]
description = "CLI for akello.io"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    "Programming Language :: Python :: 3",
]
dependencies = [
    'click',
    'boto3'
]

[project.urls]
Homepage = "https://akello.io"
Issues = "https://github.com/akello-io/akello/issues"

[project.scripts]
akello = "akellocli.akello:cli()"
