name: Deploy Storybook
run-name: ${{ github.actor }} is deploying storybook to storybook.akello.io 🚀
on:
  workflow_run:
    workflows: [ "Run API Server Tests" ]
    branches: [ main ]
    types:
      - completed

jobs:
  Deploy-Storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: packages/react
        run: npm install

      - name: Build node
        working-directory: packages/react
        run: npm run build-storybook

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'packages/react/storybook-static'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          DISTRIBUTION: ${{ secrets.STORYBOOK_AWS_CLOUD_FRONT_DISTRIBUTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}