name: Deploy akello.io
run-name: ${{ github.actor }} is deploying akello.io 🚀
on:
  workflow_run:
    workflows: [ "Run API Server Tests" ]
    branches: [ main ]
    types:
      - completed


jobs:
  Deploy-Public-Web:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials" Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2                       
  
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: packages/docs
        run: npm install --force

      - name: Build node
        working-directory: packages/docs
        run: npm run build


      - name: Upload to S3
        run: |
          aws s3 sync packages/docs/build s3://akello.io
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

