name: Unit Test Microservice Clinical Measurement Based Care
on: [push]
env:
  AKELLO_UNIT_TEST: true
  AWS_REGION: 'us-east-1'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.3
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies
        working-directory: microservices/clinical-model-measurement-based-care
        run: poetry install
      - name: Run unit tests | DynamoDB Adapter
        working-directory: microservices/clinical-model-measurement-based-care
        run: poetry run python -m unittest
