version: '3'

services:
  emqx1:
    image: emqx/emqx-enterprise:5.8.0
    container_name: emqx1
    environment:
      - EMQX_NODE__NAME=emqx@node1.emqx.com
      - EMQX_CLUSTER__DISCOVERY__STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.com,emqx@node2.emqx.com
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.com
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - ./emqx1_data:/opt/emqx/data

  emqx2:
    image: emqx/emqx-enterprise:5.8.0
    container_name: emqx2
    environment:
      - EMQX_NODE__NAME=emqx@node2.emqx.com
      - EMQX_CLUSTER__DISCOVERY__STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.com,emqx@node2.emqx.com
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node2.emqx.com
    volumes:
      - ./emqx2_data:/opt/emqx/data

networks:
  emqx-bridge:
    driver: bridge
