version: '3'

services:
  sensor-data-service:
    environment:
      POETRY_CACHE_DIR: /app/.cache/pypoetry
    build:
      context: ../../
      dockerfile: microservices/sensor_data_service/Dockerfile
    ports:
      - "8011:8000"
    volumes:
      - ../../microservices/sensor_data_service:/app/microservices/sensor_data_service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network
    depends_on:
      - kafka-ui

networks:
  app_network:
    external: true
